### PR TITLE
Added confirmation to donate

### PR DESCRIPTION
**Pull request by Revadike**
Are you fucking me? You know how easy it is to misclick? You own me a fucking steam key...
It is really hard to believe to me that you didn't do this on purpose.

### CODE REVIEW

**Comment by RedSparr0w** [comment]
Wow no need to act like that, I don't owe you shit.
Also it's not like I activate it straight away, your key is safe. Don't act so immature.

Also adding a confirmation is just as annoying as when you have to confirm each steam key retrieved from IG,
So chances are this PR will not be merged but I will look at it later on when I have a bit more time.

Hopefully you feel as passionate about other parts of the project as you do this and can create some PRs for those too.

Enjoy your day.

Sent from my iPhone

On 31/07/2017, at 8:23 AM, Royalgamer06 <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you fucking me? You know how easy it is to misclick? You own me a fucking steam key...
It is really hard to believe to me that you didn't do this on purpose.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/RedSparr0w/IndieGala-Helper/pull/18

Commit Summary

  *   Added confirmation to donate

File Changes

  *   M indiegala.js<https://github.com/RedSparr0w/IndieGala-Helper/pull/18/files#diff-0> (26)

Patch Links:

  *   https://github.com/RedSparr0w/IndieGala-Helper/pull/18.patch
  *   https://github.com/RedSparr0w/IndieGala-Helper/pull/18.diff

**Comment by Revadike** [comment]
You better check again. The key clearly was a duplicate. You gotta have activated it straight away, because I unsuccessfully attempted to activate after I misclicked. So, yes I have the right to be pissed about it. Don't you think it is fair to have at least a warning or some method to recover?

**Comment by RedSparr0w** [comment]
> You better check again. The key clearly was a duplicate. You gotta have activated it straight away, because I unsuccessfully attempted to activate after I misclicked.

Well then you obviously got someone else's dupe key.
I don't auto activate the keys, and i haven't activated any in over a week, so your own problem and nothing to do with me.

> So, yes I have the right to be pissed about it.

Feel free to be pissed at the person who created the giveaway.
But it is still not an excuse to be so disrespectful.

> Don't you think it is fair to have at least a warning or some method to recover?

The message pops up saying exactly what the button does before you click it.
Not sure what you were trying to click that you misclicked it.
Send an email or message me on steam if it's that important,
But no need to act like a child over some game you got for free from some site.

**Comment by Revadike** [comment]
I don't know what you are talking about. I got the game link from a trade that now got messed up. I did not receive any warning. I misclicked and the key was gone (expected behaviour from your script). I thought what the hell happened. Refreshed and the key was dupe. Then I noticed the icon from your extension, checked out the code and what else am I supposed to think. Of course I get upset about that. Bottomline, I got no warning, which I think should be included.

**Comment by RedSparr0w** [comment]
image
To be honest i think the message itself is more than enough warning,
It explains exactly what the button does before clicking.

If people don't read that message, Chances are they also will not read the confirm prompt.

If the key is sent by mistake there are plenty of ways to contact me before i activate it. _(which wouldn't be for at least 1-2 weeks after anyway)_

[Email](mailto:admin@redsparr0w.com)
[Steam](http://steamcommunity.com/id/RedSparr0w)

**Comment by Revadike** [comment]
Except the message doesn't show if you click instantly.... And as I said, the key is duplicate, so either you redeemed it or indiegala sent a duplicate key.

**Comment by RedSparr0w** [comment]
Well i **100%** did not redeem the key if it was sent within the last week or 2.

Could you email me the details of it though, so i can remove it from the database.

**Comment by Revadike** [comment]
I saw you record steamid and this is mine: 76561198042965266
Alright, thank you for your cooperation. We contacted indiegala support.

**Comment by RedSparr0w** [comment]
Is that the steam id you have for the "Owned Games Check" thing because i can't see it in the database, it may have never actually came through.

I'm assuming you sent it just before creating this PR.

The latest key in the DB is "Battleplan: American Civil War", is that the one?

**Comment by Revadike** [comment]
No it was this one:
`[30-07-2017 22:10:31.447] Steam Key: 7RVPW-XXXXX-Q2DNR | Result: DuplicateActivationCode (Fail) | Packages: { 84382: Shakedown Racing One }`

**Comment by Revadike** [comment]
Looks like this might be the culprit that started this whole misunderstanding: https://www.reddit.com/r/GameDealsMeta/comments/50lbc5/psa_shakedown_racing_developer_deactivated_all/

**Comment by RedSparr0w** [comment]
Can't find it in the database at all, not quite sure why it didn't come through.

> Looks like [this](https://www.reddit.com/r/GameDealsMeta/comments/50lbc5/psa_shakedown_racing_developer_deactivated_all/) might be the culprit that started this whole misunderstanding

Glad to see you found the problem [=

**Pull request closed without merging**
